package com.xiaoyun.main.mapper;

import com.xiaoyun.main.model.Meal;
import com.xiaoyun.main.model.MealKey;

public interface MealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(MealKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal
     *
     * @mbggenerated
     */
    int insert(Meal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal
     *
     * @mbggenerated
     */
    int insertSelective(Meal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal
     *
     * @mbggenerated
     */
    Meal selectByPrimaryKey(MealKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Meal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Meal record);
}