package com.xiaoyun.main.model;

import java.io.Serializable;

public class MealKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meal.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meal.manageId
     *
     * @mbggenerated
     */
    private Long manageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meal
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meal.id
     *
     * @return the value of meal.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meal.id
     *
     * @param id the value for meal.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meal.manageId
     *
     * @return the value of meal.manageId
     *
     * @mbggenerated
     */
    public Long getManageid() {
        return manageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meal.manageId
     *
     * @param manageid the value for meal.manageId
     *
     * @mbggenerated
     */
    public void setManageid(Long manageid) {
        this.manageid = manageid;
    }
}