package com.xiaoyun.main.model;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderSerialNum
     *
     * @mbggenerated
     */
    private String orderserialnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.meaId
     *
     * @mbggenerated
     */
    private Integer meaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderStatus
     *
     * @mbggenerated
     */
    private String orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.payStatus
     *
     * @mbggenerated
     */
    private String paystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.actualAmount
     *
     * @mbggenerated
     */
    private Integer actualamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.payAmount
     *
     * @mbggenerated
     */
    private Integer payamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.payType
     *
     * @mbggenerated
     */
    private String paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.userId
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.managerId
     *
     * @mbggenerated
     */
    private Long managerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderSerialNum
     *
     * @return the value of order.orderSerialNum
     *
     * @mbggenerated
     */
    public String getOrderserialnum() {
        return orderserialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderSerialNum
     *
     * @param orderserialnum the value for order.orderSerialNum
     *
     * @mbggenerated
     */
    public void setOrderserialnum(String orderserialnum) {
        this.orderserialnum = orderserialnum == null ? null : orderserialnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.meaId
     *
     * @return the value of order.meaId
     *
     * @mbggenerated
     */
    public Integer getMeaid() {
        return meaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.meaId
     *
     * @param meaid the value for order.meaId
     *
     * @mbggenerated
     */
    public void setMeaid(Integer meaid) {
        this.meaid = meaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderStatus
     *
     * @return the value of order.orderStatus
     *
     * @mbggenerated
     */
    public String getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderStatus
     *
     * @param orderstatus the value for order.orderStatus
     *
     * @mbggenerated
     */
    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus == null ? null : orderstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.payStatus
     *
     * @return the value of order.payStatus
     *
     * @mbggenerated
     */
    public String getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.payStatus
     *
     * @param paystatus the value for order.payStatus
     *
     * @mbggenerated
     */
    public void setPaystatus(String paystatus) {
        this.paystatus = paystatus == null ? null : paystatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.actualAmount
     *
     * @return the value of order.actualAmount
     *
     * @mbggenerated
     */
    public Integer getActualamount() {
        return actualamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.actualAmount
     *
     * @param actualamount the value for order.actualAmount
     *
     * @mbggenerated
     */
    public void setActualamount(Integer actualamount) {
        this.actualamount = actualamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.payAmount
     *
     * @return the value of order.payAmount
     *
     * @mbggenerated
     */
    public Integer getPayamount() {
        return payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.payAmount
     *
     * @param payamount the value for order.payAmount
     *
     * @mbggenerated
     */
    public void setPayamount(Integer payamount) {
        this.payamount = payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.payType
     *
     * @return the value of order.payType
     *
     * @mbggenerated
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.payType
     *
     * @param paytype the value for order.payType
     *
     * @mbggenerated
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.userId
     *
     * @return the value of order.userId
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.userId
     *
     * @param userid the value for order.userId
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.managerId
     *
     * @return the value of order.managerId
     *
     * @mbggenerated
     */
    public Long getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.managerId
     *
     * @param managerid the value for order.managerId
     *
     * @mbggenerated
     */
    public void setManagerid(Long managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.createTime
     *
     * @return the value of order.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.createTime
     *
     * @param createtime the value for order.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.updateTime
     *
     * @return the value of order.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.updateTime
     *
     * @param updatetime the value for order.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}